title: eComStart
email: hello@ecomstart.io
description: >- 
  Your one-stop shop for Shopify knowledge
baseurl: "" # Leave blank for root or set for subdirectory
url: "https://ecomstart.github.io" # Update with your site URL

# Minima theme configurations
theme: minima
minima:
  date_format: "%b %-d, %Y" # Example: Jan 1, 2023

# Plugins (optional for GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md
  - contact.md
