title: Your Site Title
email: your-email@example.com
description: >- 
  A simple description of your site.
baseurl: "" # Leave blank for root or set for subdirectory
url: "https://your-username.github.io" # Update with your site URL

# Minima theme configurations
theme: minima
minima:
  date_format: "%b %-d, %Y" # Example: Jan 1, 2023

# Plugins (optional for GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
